name: colorpalette
description: ryota2357's color palette (using material color).
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  pedantic_mono: ^1.20.0

dependencies:
  args: ^2.3.1
